---
abstract: 'Simple HTTP Proxy which serves some paths from locations on local disk.'
author:
  - 'Tomas Doran, <bobtfish@bobtfish.net>'
build_requires:
  Test::MockObject: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: HTTP::Proxy::Selective
name: HTTP-Proxy-Selective
no_index:
  directory:
    - inc
    - t
requires:
  Config::Tiny: 0
  File::Slurp: 0
  File::Temp: 0
  HTTP::Headers: 1.64
  HTTP::Proxy: 0.22
  IO::Socket::SSL: 0
  Net::SSLeay: 0
  Path::Class: 0
version: 0.7
